language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: nqeIKE8yvZnZRrvfTxxFJ+plp6zYF7FPvN9rPDAsDMEymsCyWm9lEkvntnni0yKl7GlgUtZ/M3Qj05rF8GAlTt7oCkfRM3ykr1HwphcOBmFfhjsxBubXyU2uNn+GDYiRP1ozDrk2PqwzSfVPD+Wu2IHmMv4mJBuYAU2BlfAXDn/1bU9WLyaqaU5YohyEvXKll/sllglDj8xi93amxBRYrn76tVKNasdqJui+L2Gq68TvOP4DyhXmmNo8GNz1fkqa8hXC8GF7HHlB7rcyGZ5+q0oDOJJHlb6Ipw3ZlQOD1EELeEOZzbQJ08J78VXBgjOuIApEx1EvM9lAYIAPbCCcSJ/NcALwDkSj+ebWSQ35W5sLznhmATGePGohpnQXGanWHXYRbnFQYRi0HE6DxWtxlrQy7X9awXS5BthIgMA8wnupjgbXigs6d3RlW2R+Vo89pc1f7o4liguVMu+CN1CM1fK/eXVzj2YcbAgLym4aixcfPdkw+9dw1p5WLI5+Y6InHGb/P+LRYAen+5POJ42dP8hCGqvGkfqp/C++Tb+Fmr4ceBxVOLk4HsP0bAlsUG8TcSVBxOoQ9DMFj+G+h+sLihsXrNL/78OsQi/9Jqvf7GsDCP/Rsb/tYHbYnesPwaHTeRHhDdt3PGJs0jAurlrh72pk0Su1fLxMwHEWmUlVslU=
